### ISSUE TITLE
Nested properties

### ISSUE THREAD

**Issue by slaskis** [mapbox/feature-filter#13]
I can't find anything about support for nested properties in the GL spec so I'm just curious if it's something you'd like to support. 

Since a GeoJSON properties object can be any JSON I'd expect to be able to filter on nested properties as well. 

Maybe something that would work like this?:

```
featureFilter([
  'all', [
    '>=', 'duration.min', 500,
    '<=', 'duration.max', 1000
  ]
])({
properties: {
  duration: {
    min: 530,
    max: 800
  }
}); // = true!
```

I realise the issue is possible conflicts with a key named `duration.max` in this case so maybe use a "magic key" similar to `$type`?

Obviously another solution to this would be to flatten the properties JSON using something like https://github.com/hughsk/flat but sometimes that's not an option.

Cheers!

**Comment by mourner** [comment]
Personally I'd prefer to leave this unsupported for now (and suggest flattening) because it would increase complexity considerably while probably degrading filtering performance. Perhaps if we can find an easy way to support it...

**Comment by slaskis** [comment]
Right, it'll obviously be a few more instructions per filter but most of the "nesting logic" would mostly be done while compiling.

Correct me if I'm wrong but what would need to be done is that instead of generating a filter function like (ignoring type checking for now):
```
return (f.properties || {})['duration.min'] >= x;
```
it would recursively generate a function like:
```
return ((f.properties || {})['duration'] || {})['min'] >= x;
```

But yeah, I totally understand if this is unnecessary complexity for this project. I personally chose to go with the flattening option myself for now.

**Comment by jfirebaugh** [comment]
Correct, this isn't supported here because filtering on nested properties is not part of the style specification.
