### ISSUE TITLE
Handle filters like [ "==" , key, "*"]

### ISSUE THREAD

**Issue by arunasank** [mapbox/feature-filter#18]
#### Steps to Trigger Behavior
Create a filter spec like so: 
`[ '==', 'highway', '*']`

This sort of `<key>=*` spec is pretty common in OSM.

-------------------------

#### Expected Behavior
 Filters all features that have the highway tag, irrespective of the value. So features having a `highway=primary`, `highway=secondary`, `highway=residential` or `highway=<anything>` would get filtered.

-------------------------

#### Actual Behaviour
They don't get filtered.

**Comment by tmcw** [comment]
Upstream issue is this one: https://github.com/mapbox/mapbox-gl-style-spec/issues/364 (feature-filter implements filters like the style-spec specifies them, so extensions are discussed in the style-spec repo)

**Comment by mourner** [comment]
This is implemented in https://github.com/mapbox/feature-filter/pull/15, just needs a merge + version bump. @lucaswoj?

**Comment by arunasank** [comment]
Fixed in #15. Closing!
