### ISSUE TITLE
Support filtering tiles from geojson-vt

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/feature-filter#20]
For whatever reason geojson-vt generates vector tiles with geojson properties mapped to the `tags` property. This module used to check for `f.tags` and it is still mentioned in the code comments but it was removed: https://github.com/mapbox/feature-filter/pull/12#r51309070 - looks like nobody could remember why it was there. It would be good to support filtering tiles generated by geojson-vt, either by changing geojson-vt to use `properties` (which would also require changes to vt-pbf) or changing this back to check `f.tags` too.

**Comment by lucaswoj** [comment]
Migrated to https://github.com/mapbox/mapbox-gl-style-spec/issues/640
