### ISSUE TITLE
support for regex pattern match

### ISSUE THREAD

**Issue by fuzhenn** [mapbox/feature-filter#21]
It is very useful in many cases, providing capabilities to filter features by regex matching.

e.g.

```javascript
// will match a feature whose prop0 matches pattern.
var filter = ['match', 'prop0', 'pattern'];
```

**Comment by tmcw** [comment]
This module tracks implemented and accepted features of the style spec (it implements filtering based on the style spec). The addition of regular expressions to the style spec is tracked at https://github.com/mapbox/mapbox-gl-style-spec/issues/233 and does not yet have consensus or a plan.

**Comment by fuzhenn** [comment]
Thanks for the reply, will keep track of it. 😺
