### ISSUE TITLE
Non-eval'ing method

### ISSUE THREAD

**Issue by tmcw** [mapbox/feature-filter#6]
The usage of the `Function` constructor in this module means that [mapbox-gl-js](https://www.mapbox.com/mapbox-gl-js/) upstream cannot satisfy the [Content Security Policy](http://www.html5rocks.com/en/tutorials/security/content-security-policy/) `unsafe-eval` rule. For CSP-implementing sites, a non-eval'ing method would better.

**Comment by jfirebaugh** [comment]
It would be possible to feature detect this and fall back to an interpreted implementation:

```
// Are we running under a CSP that forbids unsafe-eval?
try {
  new Function('');
  module.exports = require('./compiled'); // No; use fast eval'ing implementation
} catch (e) {
  module.exports = require('./interpreted); // Yes; use slower interpreted implementation
}
```

But it would be preferable not to introduce a performance variable and use a sufficiently well performing, eval-free implementation everywhere.

**Comment by jfirebaugh** [comment]
Feature detecting probably spams CSP violation reports though, huh?
